services:
  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - PAYMENTS_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=frontend
      - ENABLE_TRACING=1
    depends_on:
      - productcatalogservice
      - currencyservice
      - shoppingassistantservice
      - cartservice
      - recommendationservice
      - checkoutservice
      - adservice
      - paymentservice
      - emailservice
      - otel-collector
    networks:
      - monitoring

  shoppingassistantservice:
    build: ./src/shoppingassistantservice
    container_name: shoppingassistantservice
    environment:
      - PORT=8080
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=shoppingassistantservice
      - ENABLE_TRACING=1
    ports:
      - "8081:8080"
    networks:
      - monitoring
  productcatalogservice:
    build: ./src/productcatalogservice
    container_name: productcatalogservice
    environment:
      - PORT=3550
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=productcatalogservice
      - ENABLE_TRACING=1
    ports:
      - "3550:3550"
    networks:
      - monitoring
  currencyservice:
    build: ./src/currencyservice
    container_name: currencyservice
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=currencyservice
      - ENABLE_TRACING=1
    networks:
      - monitoring
  cartservice:
    build: ./src/cartservice/src
    container_name: cartservice
    ports:
      - "7070:7070"
    environment:
      - PORT=7070
      - REDIS_ADDR=redis-cart:6379
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=cartservice
      - ENABLE_TRACING=1
    networks:
      - monitoring
  shippingservice:
    build: ./src/shippingservice
    container_name: shippingservice
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=shippingservice
      - ENABLE_TRACING=1
    depends_on:
      - redis-cart
    networks:
      - monitoring
  recommendationservice:
    build: ./src/recommendationservice
    container_name: recommendationservice
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=recommendationservice
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - ENABLE_TRACING=1
    networks:
      - monitoring
    depends_on:
      - productcatalogservice
  checkoutservice:
    build: ./src/checkoutservice
    container_name: checkoutservice
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=checkoutservice
      - ENABLE_TRACING=1
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - shippingservice
      - paymentservice
      - emailservice
    networks:
      - monitoring
  adservice:
    build: ./src/adservice
    container_name: adservice
    ports:
      - "9555:9555"
    environment:
      - PORT=9555
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=adservice
      - ENABLE_TRACING=1
    networks:
      - monitoring
  paymentservice:
    build: ./src/paymentservice
    container_name: paymentservice
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=paymentservice
      - ENABLE_TRACING=1
    networks:
      - monitoring
  emailservice:
    build: ./src/emailservice
    container_name: emailservice
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=emailservice
      - ENABLE_TRACING=1
    networks:
      - monitoring
  redis-cart:
    image: redis:alpine
    container_name: redis-cart
    ports:
      - "6379:6379"
    networks:
      - monitoring
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reddit_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reddit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://reddit_user:password@postgres:5432/reddit_db?sslmode=disable"
    networks:
      - monitoring
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"
    networks:
      - monitoring
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - monitoring
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - postgres
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

volumes:
  grafana_data:
  prometheus_data:
  postgres_data:


networks:
  monitoring:
    driver: bridge
