global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
- job_name: 'microservices'
    static_configs:
      - targets: 
          - 'frontend:8080'
          - 'checkoutservice:5050'
          - 'productcatalogservice:3550'
          - 'currencyservice:7000'
          - 'shippingservice:50051'
          - 'cartservice:7070'
          - 'recommendationservice:8080'
          - 'adservice:9555'
          - 'paymentservice:50051'
          - 'emailservice:8080'
          - 'postgres-exporter:9187'
          - 'otel-collector:8889'
          - 'postgres:5432'
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # Postgres Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
